spring.application.name=Hueco

# data.sql se ejecuta después de que Hibernate cree las tablas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

hueco.zona-horaria=Europe/Madrid
