// Todos los textos fijos de la interfaz
export default {
  nav: {
    inicio: 'Ir al inicio',
    servicios: 'Servicios',
    sobreNosotros: 'Sobre nosotros',
    contacto: 'Contacto',
    reservar: 'Reservar',
    abrirMenu: 'Abrir menú',
    cerrarMenu: 'Cerrar menú',
    menu: 'Menú',
    iniciarSesion: 'Iniciar sesión',
  },
  hero: {
    esloganPorDefecto: 'Reserva tu cita en un momento',
    reservarCita: 'Reservar cita',
    llamar: 'Llamar',
  },
  estadoHoy: {
    abierto: (hora) => `Abierto hoy hasta las ${hora}`,
    abreHoy: (hora) => `Hoy abrimos a las ${hora}`,
    cerrado: 'Cerrado',
    // dia es "lunes" o, si falta más de una semana, "5 de enero"
    proximaApertura: (dia, hora) => `Cerrado · Abrimos el ${dia} a las ${hora}`,
  },
  dias: {
    MONDAY: 'lunes',
    TUESDAY: 'martes',
    WEDNESDAY: 'miércoles',
    THURSDAY: 'jueves',
    FRIDAY: 'viernes',
    SATURDAY: 'sábado',
    SUNDAY: 'domingo',
  },
  barra: {
    servicios: (n) => (n === 1 ? '1 servicio' : `${n} servicios`),
    continuar: 'Continuar',
  },
  errores: {
    servicios: 'No podemos mostrar los servicios ahora mismo',
    llamar: 'Llamar para reservar',
  },
  carta: {
    titulo: 'Servicios',
    ayuda: 'Toca un servicio para empezar tu reserva con él.',
  },
  sobreNosotros: {
    titulo: 'Sobre nosotros',
  },
  opiniones: {
    titulo: 'Lo que dicen nuestros clientes',
  },
  contacto: {
    titulo: 'Contacto',
    direccion: 'Dirección',
    comoLlegar: 'Cómo llegar',
    telefono: 'Teléfono',
    email: 'Email',
    horario: 'Horario',
    cerrado: 'Cerrado',
    hoy: 'hoy',
    redes: 'Síguenos',
    cierreUnDia: (fecha) => `Cerrado el ${fecha}`,
    cierreVariosDias: (desde, hasta) => `Cerrado del ${desde} al ${hasta}`,
    redNombres: {
      INSTAGRAM: 'Instagram',
      FACEBOOK: 'Facebook',
      TIKTOK: 'TikTok',
      WHATSAPP: 'WhatsApp',
      X: 'X',
      YOUTUBE: 'YouTube',
    },
  },
  footer: {
    derechos: 'Todos los derechos reservados.',
  },
  reservar: {
    pasos: ['Servicios', 'Fecha y hora', 'Tus datos y confirmar'],
    paso: (n, total) => `Paso ${n} de ${total}`,
    tituloServicios: 'Elige tus servicios',
    ayudaServicios: 'Puedes elegir varios. Verás el tiempo y el precio total abajo.',
    categorias: 'Categorías',
    otros: 'Otros',
    tituloHorario: 'Elige fecha y hora',
    cambiar: 'Cambiar',
    horasDel: (dia) => `Horas del ${dia}`,
    elegirHora: 'Elige una hora para continuar.',
    manana: 'Mañana',
    tarde: 'Tarde',
    leyenda: 'Tachado: completo · Gris: cerrado · Muy claro: aún no se puede reservar',
    estadoDia: {
      LIBRE: 'con horas libres',
      COMPLETO: 'completo',
      CERRADO: 'cerrado',
      FUERA: 'no disponible todavía',
    },
    sinHuecos: (dias) => `No quedan horas libres en los próximos ${dias} días`,
    errorHuecos: 'No podemos mostrar las horas ahora mismo',
    tituloDatos: 'Tus datos',
    cuando: 'Cuándo',
    cambiarFecha: 'Cambiar fecha u hora',
    proximamenteDatos: 'Próximamente: tus datos y confirmar',
    tusServicios: 'Tus servicios',
    total: 'Total',
  },
  login: {
    titulo: 'Iniciar sesión',
    proximamente: 'Próximamente podrás entrar para ver y gestionar tus citas.',
  },
  noEncontrado: {
    titulo: 'Página no encontrada',
    texto: 'La página que buscas no existe o se ha movido.',
    volver: 'Volver al inicio',
  },
}
