// Todos los textos fijos de la interfaz
export default {
  nav: {
    inicio: 'Ir al inicio',
    servicios: 'Servicios',
    sobreNosotros: 'Sobre nosotros',
    contacto: 'Contacto',
    reservar: 'Reservar',
    abrirMenu: 'Abrir menú',
    cerrarMenu: 'Cerrar menú',
    menu: 'Menú',
    iniciarSesion: 'Iniciar sesión',
  },
  hero: {
    esloganPorDefecto: 'Reserva tu cita en un momento',
    reservarCita: 'Reservar cita',
    llamar: 'Llamar',
  },
  estadoHoy: {
    abierto: (hora) => `Abierto hoy hasta las ${hora}`,
    abreHoy: (hora) => `Hoy abrimos a las ${hora}`,
    cerrado: 'Cerrado',
    // dia es "lunes" o, si falta más de una semana, "5 de enero"
    proximaApertura: (dia, hora) => `Cerrado · Abrimos el ${dia} a las ${hora}`,
  },
  dias: {
    MONDAY: 'lunes',
    TUESDAY: 'martes',
    WEDNESDAY: 'miércoles',
    THURSDAY: 'jueves',
    FRIDAY: 'viernes',
    SATURDAY: 'sábado',
    SUNDAY: 'domingo',
  },
  barra: {
    servicios: (n) => (n === 1 ? '1 servicio' : `${n} servicios`),
    continuar: 'Continuar',
  },
  errores: {
    servicios: 'No podemos mostrar los servicios ahora mismo',
    llamar: 'Llamar para reservar',
  },
  carta: {
    titulo: 'Servicios',
    ayuda: 'Toca un servicio para empezar tu reserva con él.',
  },
  sobreNosotros: {
    titulo: 'Sobre nosotros',
  },
  opiniones: {
    titulo: 'Lo que dicen nuestros clientes',
  },
  contacto: {
    titulo: 'Contacto',
    direccion: 'Dirección',
    comoLlegar: 'Cómo llegar',
    telefono: 'Teléfono',
    email: 'Email',
    horario: 'Horario',
    cerrado: 'Cerrado',
    hoy: 'hoy',
    redes: 'Síguenos',
    cierreUnDia: (fecha) => `Cerrado el ${fecha}`,
    cierreVariosDias: (desde, hasta) => `Cerrado del ${desde} al ${hasta}`,
    redNombres: {
      INSTAGRAM: 'Instagram',
      FACEBOOK: 'Facebook',
      TIKTOK: 'TikTok',
      WHATSAPP: 'WhatsApp',
      X: 'X',
      YOUTUBE: 'YouTube',
    },
  },
  footer: {
    derechos: 'Todos los derechos reservados.',
    privacidad: 'Privacidad',
  },
  // Plantilla: cada comercio la adapta con su responsable, conservación y contacto (issue #34)
  privacidad: {
    titulo: 'Política de privacidad',
    secciones: [
      {
        titulo: 'Quién trata tus datos',
        texto: 'El responsable es el comercio que aparece en esta web. Puedes contactar con él en la dirección, el teléfono o el email de la sección Contacto.',
      },
      {
        titulo: 'Para qué los usamos',
        texto: 'Usamos tu nombre, tu teléfono y, si nos lo das, tu email solo para gestionar las citas que pides: reservarlas y avisarte si hay algún cambio. No los usamos para publicidad ni se los damos a nadie.',
      },
      {
        titulo: 'Por qué podemos usarlos',
        texto: 'Porque los necesitamos para darte el servicio que nos pides al reservar.',
      },
      {
        titulo: 'Cuánto tiempo los guardamos',
        texto: 'Mientras seas cliente y, después, el tiempo que obligue la ley.',
      },
      {
        titulo: 'Tus derechos',
        texto: 'Puedes pedir ver, corregir o borrar tus datos, o que dejemos de usarlos, contactando con el comercio. También puedes reclamar ante la Agencia Española de Protección de Datos (aepd.es).',
      },
    ],
  },
  reservar: {
    pasos: ['Servicios', 'Fecha y hora', 'Tus datos y confirmar'],
    paso: (n, total) => `Paso ${n} de ${total}`,
    tituloServicios: 'Elige tus servicios',
    ayudaServicios: 'Puedes elegir varios. Verás el tiempo y el precio total abajo.',
    categorias: 'Categorías',
    otros: 'Otros',
    tituloHorario: 'Elige fecha y hora',
    cambiar: 'Cambiar',
    horasDel: (dia) => `Horas del ${dia}`,
    elegirHora: 'Elige una hora para continuar.',
    manana: 'Mañana',
    tarde: 'Tarde',
    leyenda: 'Tachado: completo · Gris: cerrado · Muy claro: aún no se puede reservar',
    estadoDia: {
      LIBRE: 'con horas libres',
      COMPLETO: 'completo',
      CERRADO: 'cerrado',
      FUERA: 'no disponible todavía',
    },
    sinHuecos: (dias) => `No quedan horas libres en los próximos ${dias} días`,
    errorHuecos: 'No podemos mostrar las horas ahora mismo',
    tituloDatos: 'Tus datos',
    tituloFormulario: '¿A nombre de quién?',
    cuando: 'Cuándo',
    cambiarFecha: 'Cambiar fecha u hora',
    campos: {
      nombre: 'Nombre',
      telefono: 'Teléfono',
      email: 'Email',
      notas: 'Notas para el comercio',
      opcional: '(opcional)',
    },
    ayudaNotas: 'Por ejemplo: pelo muy largo, vengo con mi hija…',
    errores: {
      nombre: 'Escribe tu nombre',
      telefono: 'Escribe un teléfono de 9 cifras',
      email: 'Revisa el email',
      notas: (max) => `Como mucho ${max} caracteres`,
      cita: 'Revisa la fecha, la hora y los servicios de tu cita.',
    },
    privacidad: 'Usaremos tus datos solo para gestionar esta cita.',
    verPrivacidad: 'Política de privacidad',
    confirmar: 'Confirmar cita',
    confirmando: 'Confirmando…',
    horaOcupada: 'Esa hora se acaba de ocupar. Elige otra y no tendrás que volver a escribir tus datos.',
    elegirOtraHora: 'Elegir otra hora',
    limiteTelefono: 'Ya tienes el máximo de citas pendientes con este teléfono. Llama para reservar más.',
    limiteIp: 'Se han hecho muchas reservas seguidas desde tu conexión. Inténtalo más tarde o llama.',
    errorEnvio: 'No hemos podido confirmar la cita. Inténtalo de nuevo o llama.',
    confirmada: '¡Cita confirmada!',
    confirmadaTexto: 'Te esperamos. Guarda esta página o añade la cita a tu calendario.',
    anadirCalendario: 'Añadir a mi calendario',
    cambiarLlamando: 'Para cambiar o cancelar la cita, llama al',
    cambiarSoloLlamando: 'Para cambiarla, llama al',
    cancelarCita: 'Cancelar cita',
    cancelarPregunta: (fecha, hora) => `¿Cancelar la cita del ${fecha} a las ${hora}?`,
    cancelarAviso: 'La hora quedará libre para otra persona.',
    cancelarSi: 'Sí, cancelarla',
    cancelarNo: 'No, mantenerla',
    cancelando: 'Cancelando…',
    cancelarError: 'No hemos podido cancelarla. Inténtalo de nuevo o llama.',
    cancelarFueraDePlazo: 'Queda poco para tu cita y ya no se puede cancelar desde la web. Llama al comercio.',
    citaCancelada: 'Cita cancelada',
    canceladaTexto: 'La hora ha quedado libre. Si quieres, puedes reservar otra.',
    reservarOtra: 'Reservar otra cita',
    tusServicios: 'Tus servicios',
    total: 'Total',
  },
  login: {
    titulo: 'Iniciar sesión',
    proximamente: 'Próximamente podrás entrar para ver y gestionar tus citas.',
  },
  noEncontrado: {
    titulo: 'Página no encontrada',
    texto: 'La página que buscas no existe o se ha movido.',
    volver: 'Volver al inicio',
  },
  agenda: {
    titulo: 'Agenda',
    usuario: 'Usuario',
    clave: 'Clave',
    entrar: 'Entrar',
    entrando: 'Entrando…',
    claveIncorrecta: 'Usuario o clave incorrectos',
    errorConexion: 'No se ha podido cargar la agenda. Inténtalo de nuevo.',
    salir: 'Salir',
    anterior: 'Semana anterior',
    siguiente: 'Semana siguiente',
    hoy: 'Hoy',
    esHoy: 'hoy',
    cerrado: 'Cerrado',
    sinCitas: 'Sin citas',
    sinCliente: 'Sin cliente',
    estados: {
      PENDIENTE: 'Pendiente',
      CONFIRMADA: 'Confirmada',
      CANCELADA: 'Cancelada',
      COMPLETADA: 'Completada',
      NO_SHOW: 'No vino',
    },
  },
}
