-- Esquema tal como lo creaba Hibernate antes de Flyway (export DDL para PostgreSQL),
-- con nombres legibles en las restricciones. Las mejoras van en migraciones posteriores.

CREATE TABLE negocio (
    id             bigint       NOT NULL,
    eslogan        varchar(255),
    sobre_nosotros text,
    direccion      varchar(255),
    telefono       varchar(255),
    email          varchar(255),
    CONSTRAINT pk_negocio PRIMARY KEY (id)
);

CREATE TABLE negocio_horario (
    negocio_id bigint NOT NULL,
    dia_semana varchar(255),
    apertura   time(0),
    cierre     time(0),
    CONSTRAINT ck_negocio_horario_dia_semana
        CHECK (dia_semana IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    CONSTRAINT fk_negocio_horario_negocio FOREIGN KEY (negocio_id) REFERENCES negocio (id)
);

CREATE TABLE negocio_cierre (
    negocio_id bigint NOT NULL,
    desde      date,
    hasta      date,
    motivo     varchar(255),
    CONSTRAINT fk_negocio_cierre_negocio FOREIGN KEY (negocio_id) REFERENCES negocio (id)
);

CREATE TABLE negocio_red_social (
    negocio_id bigint NOT NULL,
    tipo       varchar(255),
    url        varchar(255),
    CONSTRAINT ck_negocio_red_social_tipo
        CHECK (tipo IN ('INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'WHATSAPP', 'X', 'YOUTUBE')),
    CONSTRAINT fk_negocio_red_social_negocio FOREIGN KEY (negocio_id) REFERENCES negocio (id)
);

CREATE TABLE negocio_testimonio (
    negocio_id bigint NOT NULL,
    autor      varchar(255),
    texto      varchar(255),
    orden      integer,
    CONSTRAINT fk_negocio_testimonio_negocio FOREIGN KEY (negocio_id) REFERENCES negocio (id)
);

CREATE TABLE servicio (
    id               bigint GENERATED BY DEFAULT AS IDENTITY,
    nombre           varchar(255),
    descripcion      varchar(160),
    duracion_minutos integer NOT NULL,
    precio           numeric(38, 2),
    activo           boolean NOT NULL,
    categoria        varchar(255),
    orden            integer NOT NULL,
    CONSTRAINT pk_servicio PRIMARY KEY (id)
);

CREATE TABLE cliente (
    cliente_id bigint GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(255),
    telefono   varchar(255),
    email      varchar(255),
    creado_en  timestamp(6),
    CONSTRAINT pk_cliente PRIMARY KEY (cliente_id),
    CONSTRAINT uk_cliente_telefono UNIQUE (telefono)
);

CREATE TABLE cita (
    id               bigint GENERATED BY DEFAULT AS IDENTITY,
    fecha            date,
    hora             time(0),
    estado           varchar(255),
    cliente_id       bigint,
    duracion_minutos integer        NOT NULL,
    precio_total     numeric(38, 2) NOT NULL,
    notas            varchar(300),
    token            varchar(36),
    CONSTRAINT pk_cita PRIMARY KEY (id),
    CONSTRAINT uk_cita_token UNIQUE (token),
    CONSTRAINT ck_cita_estado
        CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA', 'NO_SHOW')),
    CONSTRAINT fk_cita_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (cliente_id)
);

CREATE TABLE cita_servicio (
    cita_id     bigint NOT NULL,
    servicio_id bigint NOT NULL,
    CONSTRAINT fk_cita_servicio_cita FOREIGN KEY (cita_id) REFERENCES cita (id),
    CONSTRAINT fk_cita_servicio_servicio FOREIGN KEY (servicio_id) REFERENCES servicio (id)
);
